export { HeroSection } from './hero-section'
export { FeaturesSection } from './features-section'
export { SocialProofSection } from './social-proof-section'
export { FAQSection } from './faq-section'
export { FinalCTASection } from './final-cta-section'
